config/routes.rb
KidsToys::Application.routes.draw do



  use_doorkeeper

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match 'admin' => 'users/admin#index', :via => :get, :as => 'admin'
  match 'admin' => 'users/admin#login', :via => :post, :as => 'admin_login'
  match 'admin/users' => 'users/admin#users', :via => :get, :as => 'admin_users'
  match 'admin/update_user/:id' => 'users/admin#update_user', :via => [:put, :post], :as => 'admin_update_user'
  match 'admin/delete_user/:id' => 'users/admin#delete_user', :via => [:delete], :as => 'admin_delete_user'
  match 'admin/schools' => 'users/admin#schools', :via => :get, :as => 'admin_schools'
  match 'admin/notifications' => 'users/admin#notifications', :via => :get, :as => 'admin_notifications'
  match 'admin/logout' => 'users/admin#logout', :via => [:get, :delete], :as => 'admin_logout'

  match 'question_answers/update_all' => 'question_answers#update_all', via: [:put, :post], as: 'update_all_question_answers'
  resources :question_answers, except:[:show]

  resources :item_comments

  resources :cart_items, module: 'carts'

  match 'schools/admin' => 'schools#admin', :via => :get, :as => :schools_admin
  match 'schools/admin/:id' => 'schools#admin_edit', :via => :get, :as =>  :schools_admin_edit
  match 'schools/admin/:id' => 'schools#admin_update', :via => :post, :as => :schools_admin_update
  match 'schools/admin/:id' => 'schools#admin_destroy', :via=> :delete, :as => :schools_admin_destroy
  resources :schools, path: '/schools'

  match '/demo' => 'items#demo'

  namespace :inventory do
    resources :manager, :only => [:index] do

    end
    match 'activate' => 'manager#activate', as: 'activate_item'
    match 'approve' => 'manager#approve', as: 'approve_item'
    match 'deactivate' => 'manager#deactivate', as: 'deactivate_item'
    match 'decline' => 'manager#decline', as: 'decline_item'

    match 'item_for_approval' => 'manager#item_for_approval_notice', as: 'item_for_approval_notice'
  end


  match 'admin/categories' => 'categories#admin', :as => :admin_categories
  match 'categories/update_all' => 'categories#update_all', as: :update_all_categories, via:[:put, :post]
  resources :categories

  match 'category_groups/update_all' => 'category_groups#update_all', as: :update_all_category_groups, via:[:put, :post]
  match 'category_groups/:id/add_mapping' => 'category_groups#add_mapping', as: :add_category_group_mapping, via:[:put, :post]
  match 'category_groups/:id/add_curated_category' => 'category_groups#add_curated_category', as: :add_curated_category, via:[:put, :post]
  resources :category_groups
  resources :category_group_mappings, only: [:edit, :update]

  match 'categories/:id(/:title)' => 'categories#show', :as => :category_title
  match 'user_categories' => 'categories#user_categories', :as => :user_categories

  get 'account/confirm' => 'account_confirmation#index', as: :account_confirmation
  get 'account/credit_card' => 'account_confirmation#credit_card', as: :account_credit_card
  get 'account/driver_license' => 'account_confirmation#driver_license', as: :account_driver_license
  post 'account/driver_license' => 'account_confirmation#upload_driver_license', as: :account_upload_driver_license
  post 'account/confirm/payment' => 'account_confirmation#authorize_payment', as: :account_confirmation_payment
  get 'account/confirmed' => 'account_confirmation#account_confirmed', as: :account_confirmed
  #####################
  # Trade

  resources :trades, module: 'trading', except: [:edit, :update, :create], as: 'trade'
  match 'trades/(:id)(.:format)' => 'trading/trades#create', as: 'create_trade', via: :post
  match 'trades/(:id)(.:format)' => 'trading/trades#reply', as: 'reply_trade', via: :put
  match 'trades/:id/comments(.:format)' => 'trading/trades#list_comments', as: 'trade_comments', via: :get
  match 'trades/:id/comments(.:format)' => 'trading/trades#comments', as: 'create_trade_comments', via: :post
  match 'trades/:id/accept(.:format)' => 'trading/trades#accept', as: 'accept_trade', via: :post
  match 'trades/:id/decline(.:format)' => 'trading/trades#decline', as: 'decline_trade', via: :delete
  match 'trades/:id/cancel(.:format)' => 'trading/trades#destroy', as: 'cancel_trade', via: [:put, :post, :delete]
  match 'trades/:id/pick_meeting(.:format)' => 'trading/trades#pick_meeting', as: 'pick_meeting', via: [:put, :post]
  match 'trades/:id/respond_to_meeting(.:format)' => 'trading/trades#respond_to_meeting', as: 'respond_to_meeting', via: [:put, :post]
  match 'trades/:id/confirm(.:format)' => 'trading/trades#confirm_completion', as: 'confirm_completion', via: [:put, :post]
  match 'trades/:id/pack(.:format)' => 'trading/trades#confirm_packed', as: 'confirm_packed', via: [:put, :post]
  match 'trades/:id/completed(.:format)' => 'trading/trades#completed', as: 'completed_change', via: [:put, :post]

  resources :buy_requests, module: 'trading', only: [:new, :create, :show]
  match 'buy_requests/(:id)/accept(.:format)' => 'trading/buy_requests#accept', as: 'accept_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/decline(.:format)' => 'trading/buy_requests#decline', as: 'decline_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/confirm(.:format)' => 'trading/buy_requests#confirm', as: 'confirm_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/sold(.:format)' => 'trading/buy_requests#sold', as: 'sold_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/not_sold(.:format)' => 'trading/buy_requests#not_sold', as: 'not_sold_buy_request', via: [:put, :post]

  #####################
  # Notifications

  resources :notifications, module: 'users', only: [:index, :show] do
    member do
      delete 'delete'
    end
  end
  match 'notifications/archive' => 'users/notifications#archive', as: 'archive_notifications', via: :put
  match '/notifications/push' => 'users/notifications#send_push_notification', as: 'send_push_notification', via: [:put, :post]
  match '/notifications_count(.:format)' => 'users/notifications#count', as: 'notifications_count', via: :get

  root :to => 'home#home'
  get "/home/:version" => "home#home"
  get "/terms" => "home#terms"
  get "/privacy" => "home#privacy"
  get "/privacy_and_terms" => "home#privacy_and_terms"
  get "/safety" => "home#safety"
  get "/about_us" => "home#about_us"
  get "/faq" => "home#faq"

  match 'tips/update_all' => 'tips#update_all', via: [:put, :post], as: 'update_all_tips'
  resources :tips, except: [:show]

  #####################
  # User

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {registrations: 'users', sessions: 'sessions', passwords: 'passwords'}
  devise_scope :user do
    post '/forgot_password', to: 'passwords#create'
    get '/users/password/edit', to: 'password#edit'
    put '/users/password', to: 'passwords#update'
  end
  #post '/forgot_password' => 'devise/passwords#create'
  #get '/forgot_password'=> 'devise/passwords#edit'

  # Custom routes that still use :users scope
  devise_scope :user do
    get "/users/logout" => "sessions#destroy"
    get "/users/show_current_user", as: "show_current_user"
    get "/users/dashboard", to: "users#dashboard", as: "users_dashboard"
    get "/users/friends", to: "users#friends", as: "users_friends"
    get "/users/:id/items", to: "stores#show", as: "users_items"

    get "/users/children", to: "users/children#index", as: "users_children"
    get "/users/child", to: "users/children#new", as: "users_new_child"
    match '/users/child/:id/school' => 'users/children#school', as: 'child_school', via:[:get]
    match '/users/child/:id/update_school' => 'users/children#update_school', as: 'child_update_school', via:[:put, :post]
    get "/users/child/:id", to: "users/children#edit", as: "users_edit_child"
    post "/users/child/create", to: "users/children#create", as: "users_create_child"
    post '/users/student/create', to: 'users/children#create_student', as: 'users_create_student'
    post "/users/push_notifications", to: "users/user_notification_tokens#create", as: "create_user_notification_tokens"
    post "/users/child/login", to: "users/children#login", as: "users_login_child"
    put "/users/child/:id", to: "users/children#update", as: "users_update_child"
    post "/users/sign_in_as/:id", to: "sessions#sign_in_as", as: "sign_in_as"

    get "/users/:id", to: "users#show", as: "user"
    put "/users/login(.format)", to: "sessions#new"
    put "/users" => "users#update", as: "update_user"

    get '/boundaries', to: 'users/boundaries#index', as: 'boundaries'
    put '/boundaries', to: 'users/boundaries#update', as: 'update_boundaries'

    get  '/users/potential_friends' => 'users/friend_request#index', as: 'potential_friends'
    get '/friend_request/:id' => 'users/friend_request#show', as: 'friend_request'
    post '/friend_request' => 'users/friend_request#create', as: 'create_friend_request'
    match '/friend_request/:id/accept' => 'users/friend_request#accept', as: 'accept_friend_request', via:[:put, :post]
    match '/friend_request/:id/decline' => 'users/friend_request#deny_request', as: 'deny_friend_request', via:[:put, :post]

    # Users APIs
    scope path: '/api/v1' do
      get '/users/followings', to: 'users#followings', as: 'api_get_followings'
      get '/videos/value_prop' => 'sessions#video', via: [:get]
      match '/users/logout' => 'sessions#destroy', via: [:get, :put, :delete], as: 'api_users_logout'

      get  '/users/potential_friends' => 'users/friend_request#index', as: 'api_get_potential_friends'
      post '/users/friend_request' => 'users/friend_request#create', as: 'api_create_friend_request'
      get '/users/friend_request/:id' => 'users/friend_request#show', as: 'api_show_friend_request'
      post '/users/friend_request/:id/accept' => 'users/friend_request#accept', as: 'api_accept_friend_request'

app/views/admin/delete_user.js.erb
<% if flash[:error].present? -%>
alert("Error: <%=flash[:error]%>");
<% elsif params[:hide_element].present? -%>
$("#<%= params[:hide_element] %>").fadeOut();
<% end # flash[:error], hide_element -%>

app/views/admin/index.html.haml
.container
  %h1.page-header Admin Dashboard

  .panel.panel-success
    .panel-heading
      %h4 Users
    .panel-body.list-group
      %a.list-group-item(href="/admin/users") User Registrations
      %a.list-group-item(href="/admin/notifications") Notifications Manager

  .panel.panel-info
    .panel-heading
      %h4 Categories
    .panel-body.list-group
      %a.list-group-item(href="/categories") Categories Manager
      %a.list-group-item(href="/admin/categories") Category Groups Admin

  .panel.panel-warning
    .panel-heading
      %h4 Guides
    .panel-body.list-group
      %a.list-group-item(href="/question_answers") Questions and Answers (FAQs)
      %a.list-group-item(href="/tips") Tips

app/views/admin/schools.html.haml
- search_uri = 'http://www.google.com/webhp?sourceid=chrome-instant&es_th=1ie='
- filter_all = params[:filter].to_s == 'all'
- content_for(:head_extra) do
  :css
    #schools_table { width:100%; margin:0; }
    #schools_table td { padding: 5px 10px; }

- content_for(:footer_extra) do
  :javascript
    jQuery(function(){
      /*$("#schools_search_form").submit(function(event){
        // Load search into iframe
        var school_name = $("#school_name").val().trim();
        alert(school_name);
        if (school_name != "") {
          $("#search_engine_frame")[0].src = ""+ school_name;
        }
        return false;
      }); // Cannot cross-frame load */
    });

.container
  .row.form-group(style="vertical-align:bottom; margin:0;")
    %form#schools_search_form(action="#{search_uri}" target='_blank')
      %img.pull-left(src="/assets/logos/kidstrade-title.png" alt="KIDSTrade" style="margin:0 2% 0 0;")
      %p.pull-left.normal-weight.text-medium-title(style="margin:0 2% 0 0;")
        %a(href='/admin') ADMIN
        %span.gray-title-color - SCHOOLS
      %p.pull-left(style="width:25%;")
        %input#school_name(type="text" name="q" value="#{params[:name]}" placeholder="Search Schools" style="width:80%;" )
        %button(type="submit" aria-label="Search Schools" )
          %span.glyphicon.glyphicon-search(aria-hidden="true")/
      %p.pull-right.normal-weight.text-medium-title
        %a(href="#{admin_schools_path(filter:'all')}" class="#{filter_all ? 'dark-title-color' : ''}") ALL
        \|
        %a(href="#{admin_schools_path}" class="#{filter_all ? '' : 'dark-title-color'}") Not Validated
%table#schools_table.table-striped
  %tbody
    %tr
      %td.text-small-title.gray-title-color() ID
      %td.text-small-title.gray-title-color(width="30%" ) Name
      %td.text-small-title.gray-title-color(width="15%" ) City
      %td.text-small-title.gray-title-color(width="10%" ) State/Province/Region
      %td.text-small-title.gray-title-color(width="18%" ) Zip/Postal Code
      %td.text-small-title.gray-title-color(width="15%" ) Country
    - @schools.each do|school|
      %tr
        %td.gray-title-color #{school.id}
        %td #{school.name}
        %td #{school.city}
        %td #{school.state}
        %td.moderate-dark-title-color #{school.zip}
        %td.moderate-dark-title-color #{school.country}
.section-gap
.container
  .text-center
    = pagination_links(@schools)

- if params[:name].present?
  %iframe#search_engine_frame(style="width:100%; height:80%; padding:1% 2%; border:solid 1px #cccccc;" src="#{search_uri}#{params[:name]}")

app/views/admin/update_user.js.erb
$("#is_test_user_<%=@user.id%>").addClass("highlight-border");
setTimeout(function(){ $("#is_test_user_<%=@user.id%>").removeClass("highlight-border"); }, 2000);
<% if flash[:error].present? -%>
alert("Error: <%=flash[:error]%>");
<% elsif params[:hide_element].present? -%>
$("#<%= params[:hide_element] %>").fadeOut();
<% end # flash[:error], hide_element -%>

app/views/admin/users.html.haml
- test_only = params[:test_only].to_i == 1
- Time.zone = 'Eastern Time (US & Canada)'
- content_for(:head_extra) do
  = stylesheet_link_tag 'jquery-ui'
  :css
    .users-table { border:solid 1px #cccccc; margin:3% 1%; }
    .users-table th { font-size:12pt; padding:5px; }
    .users-table td { font-size:12pt; padding:5px; }
    .highlight-border { box-shadow: 0 0 15px #33ff99;
      -webkit-box-shadow: 0 0 15px #33ff99;
      -moz-box-shadow: 0 0 15px #33ff99;
     }

  :javascript
    $(function() {
      $(".datepicker" ).datepicker({dateFormat:'yy-mm-dd' });
      $("input[type=checkbox]" ).change(function() {
          $(this).siblings("input[type=submit]").click();
        } );
      $('[data-toggle="tooltip"]').tooltip();
    });

.pull-right(style="margin: 10px 10px 0;")
  %a(href="#{admin_categories_path}") Admin / Categories
.clearfix

%table(class="users-table table table-striped" cellspacing="1" )
  %tbody
    %tr
      %td(colspan="13")
        = form_tag({test_only: test_only}, method:'get' ) do
          %h3
            Since:
            %input(type='text' name='start_time' value="#{@start_time.strftime('%Y-%m-%d %H:%M')}" placeholder="year-month-day hour:minute" class='datepicker')/
            %input(type='submit' value="Search")
          %a(href="#{request.path}.csv?test_only=#{test_only}&start_time=#{@start_time.strftime('%Y-%m-%d+%H:%M')}") CSV Export of All These Records
      %td(colspan="3" style="text-align:left;" )
        - if test_only
          = link_to('Real Users', {test_only: 0, page:1})
          '/'
          %strong Test Users
        - else
          %strong Real Users /
          = link_to('Test Users', {test_only: 1, page:1})
      %td(colspan="3" style="text-align:right")
        %a(href="#" class="glyphicon glyphicon-phone" data-toggle='modal' data-target='#send_push_modal' data-placement='right' title='Send custom notification')
        %a(href="#" data-toggle='modal' data-target='#send_push_modal' data-placement='right' title='Send custom notification') Send Notification
    %tr
      %th Test User?
      %th ID
      %th Gender
      %th user_name
      %th First Name
      %th Avatar
      %th School Name
      %th Grade
      %th Register Time
      %th Parent: First Name
      %th Parent: Last Name
      %th Parent: Email
      %th Address (joined)
      %th City
      %th State
      %th Zip
      %th Items Approved
      %th Items Pending
      %th Account confirmed?
    - @users.each do|user|
      %tr(id="user_row_#{user.id}")
        %td
          = form_for(user, as: 'user', url: admin_update_user_path(user), method:'put', remote:true, html:{id:"user_form_#{user.id}", class:'user-form', method:'put'}) do|f|
            = hidden_field_tag(:hide_element, "user_row_#{user.id}") if not test_only
            = f.check_box(:is_test_user, class:'form-control', style:'max-width:30px;', id:"is_test_user_#{user.id}",  data: user.id, |
              'data-toggle'=> 'popover', title:'Update Error') |
            = f.submit('', class:'hidden')
        %td #{user.id}
        %td(class="#{user.gender.downcase}-color") #{user.gender}
        %td
          %strong #{user.user_name}
          %br/
          = link_to(' ', admin_delete_user_path(id: user, hide_element: "user_row_#{user.id}"), remote:true, method:'delete', confirm:'Sure to delete this child?', class:'glyphicon glyphicon-remove text-danger', 'data-toggle'=>'tooltip', 'data-placement'=>'right', title:'Delete this child')
          %a(href="#" class="glyphicon glyphicon-phone" data-toggle='modal' data-target='#send_push_modal' data-placement='right' title='Send notification to this child' data="#{user.user_name}")
        %td #{user.first_name}
        %td
          %img(src="#{profile_image_thumbnail(user)}" style="max-width:56px; height:auto;")
        %td #{user.current_school.try(:name)} (#{user.current_school_id})
        %td #{::Schools::SchoolGroup::GRADES_HASH[user.grade] }
        %td #{user.created_at.in_time_zone.strftime('%m/%d/%y %l:%M %p') }
        %td #{user.parent ? user.parent.first_name : '---'}
        %td #{user.parent ? user.parent.last_name : '---'}
        %td
          #{user.parent.try(:email)}
          %br/
          = link_to(' ', admin_delete_user_path(id: user.parent_id, hide_element: "user_row_#{user.id}"), remote:true, method:'delete', confirm:'Sure to delete this parent and children?', class:'glyphicon glyphicon-remove text-danger', 'data-toggle'=>'tooltip', 'data-placement'=>'left', title:'Delete this parent and children')
        %td
          #{user.primary_user_location.try(:address)}
          %br/
          #{user.primary_user_location.try(:address2)}
        %td #{user.primary_user_location.try(:city)}
        %td #{user.primary_user_location.try(:state)}
        %td #{user.primary_user_location.try(:zip)}
        %td.text-center #{Item.open_items.where(user_id: user.id).count}
        %td.text-center #{Item.pending.where(user_id: user.id).count}
        %td #{user.parent.try(:account_confirmed?) }


.container
  .row.text-center
    = pagination_links(@users)
.container
  #send_push_modal.modal.fade(tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true")
    .modal-dialog(role="document")
      .modal-content
        = form_tag(send_push_notification_path, remote: true) do
          = hidden_field_tag('hide_element', 'send_push_modal', id:'send_push_modal');
          .modal-header
            %button.close(type="button" data-dismiss="modal" aria-label="Close")
              %span(aria-hidden="true") &times;
            %h4.modal-title Send Push Notifications
          #edit_send_push.modal-body
            .form-group
              %label(for='user_name') User Name
              %input.form-control(id='user_name' name='user_name' placeholder='User Name' )
            .form-group
              %label(for='notification_text') Message
              %textarea.form-control(id='notification_text' name='notification_text' placeholder='Message' )
          .modal-footer
            %button.btn.btn-default(type='button' data-dismiss='modal' id='send_push_modal_close') Close
            %input.btn.btn-primary(type="submit" data-disable-with="Sending..." value='Send')