config/routes.rb
  match 'user_categories' => 'categories#user_categories', :as => :user_categories

  get 'account/confirm' => 'account_confirmation#index', as: :account_confirmation
  get 'account/credit_card' => 'account_confirmation#credit_card', as: :account_credit_card
  get 'account/driver_license' => 'account_confirmation#driver_license', as: :account_driver_license
  post 'account/driver_license' => 'account_confirmation#upload_driver_license', as: :account_upload_driver_license
  post 'account/confirm/payment' => 'account_confirmation#authorize_payment', as: :account_confirmation_payment
  get 'account/confirmed' => 'account_confirmation#account_confirmed', as: :account_confirmed
  #####################
  # Trade

  resources :trades, module: 'trading', except: [:edit, :update, :create], as: 'trade'
  match 'trades/(:id)(.:format)' => 'trading/trades#create', as: 'create_trade', via: :post
  match 'trades/(:id)(.:format)' => 'trading/trades#reply', as: 'reply_trade', via: :put
  match 'trades/:id/comments(.:format)' => 'trading/trades#list_comments', as: 'trade_comments', via: :get
  match 'trades/:id/comments(.:format)' => 'trading/trades#comments', as: 'create_trade_comments', via: :post
  match 'trades/:id/accept(.:format)' => 'trading/trades#accept', as: 'accept_trade', via: :post
  match 'trades/:id/decline(.:format)' => 'trading/trades#decline', as: 'decline_trade', via: :delete
  match 'trades/:id/cancel(.:format)' => 'trading/trades#destroy', as: 'cancel_trade', via: [:put, :post, :delete]
  match 'trades/:id/pick_meeting(.:format)' => 'trading/trades#pick_meeting', as: 'pick_meeting', via: [:put, :post]
  match 'trades/:id/respond_to_meeting(.:format)' => 'trading/trades#respond_to_meeting', as: 'respond_to_meeting', via: [:put, :post]
  match 'trades/:id/confirm(.:format)' => 'trading/trades#confirm_completion', as: 'confirm_completion', via: [:put, :post]
  match 'trades/:id/pack(.:format)' => 'trading/trades#confirm_packed', as: 'confirm_packed', via: [:put, :post]
  match 'trades/:id/completed(.:format)' => 'trading/trades#completed', as: 'completed_change', via: [:put, :post]

  resources :buy_requests, module: 'trading', only: [:new, :create, :show]
  match 'buy_requests/(:id)/accept(.:format)' => 'trading/buy_requests#accept', as: 'accept_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/decline(.:format)' => 'trading/buy_requests#decline', as: 'decline_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/confirm(.:format)' => 'trading/buy_requests#confirm', as: 'confirm_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/sold(.:format)' => 'trading/buy_requests#sold', as: 'sold_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/not_sold(.:format)' => 'trading/buy_requests#not_sold', as: 'not_sold_buy_request', via: [:put, :post]

  #####################
  # Notifications

  resources :notifications, module: 'users', only: [:index, :show] do
    member do
      delete 'delete'
    end
  end
  match 'notifications/archive' => 'users/notifications#archive', as: 'archive_notifications', via: :put
  match '/notifications/push' => 'users/notifications#send_push_notification', as: 'send_push_notification', via: [:put, :post]
  match '/notifications_count(.:format)' => 'users/notifications#count', as: 'notifications_count', via: :get

  root :to => 'home#home'
  get "/home/:version" => "home#home"
  get "/terms" => "home#terms"
  get "/privacy" => "home#privacy"
  get "/privacy_and_terms" => "home#privacy_and_terms"
  get "/safety" => "home#safety"
  get "/about_us" => "home#about_us"
  get "/faq" => "home#faq"

  match 'tips/update_all' => 'tips#update_all', via: [:put, :post], as: 'update_all_tips'
  resources :tips, except: [:show]

  #####################
  # User

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {registrations: 'users', sessions: 'sessions', passwords: 'passwords'}
  devise_scope :user do
    post '/forgot_password', to: 'passwords#create'
    get '/users/password/edit', to: 'password#edit'
    put '/users/password', to: 'passwords#update'
  end
  #post '/forgot_password' => 'devise/passwords#create'
  #get '/forgot_password'=> 'devise/passwords#edit'

  # Custom routes that still use :users scope
  devise_scope :user do
    get "/users/logout" => "sessions#destroy"
    get "/users/show_current_user", as: "show_current_user"
    get "/users/dashboard", to: "users#dashboard", as: "users_dashboard"
    get "/users/friends", to: "users#friends", as: "users_friends"
    get "/users/:id/items", to: "stores#show", as: "users_items"

    get "/users/children", to: "users/children#index", as: "users_children"
    get "/users/child", to: "users/children#new", as: "users_new_child"
    match '/users/child/:id/school' => 'users/children#school', as: 'child_school', via:[:get]
    match '/users/child/:id/update_school' => 'users/children#update_school', as: 'child_update_school', via:[:put, :post]
    get "/users/child/:id", to: "users/children#edit", as: "users_edit_child"
    post "/users/child/create", to: "users/children#create", as: "users_create_child"
    post '/users/student/create', to: 'users/children#create_student', as: 'users_create_student'
    post "/users/push_notifications", to: "users/user_notification_tokens#create", as: "create_user_notification_tokens"
    post "/users/child/login", to: "users/children#login", as: "users_login_child"
    put "/users/child/:id", to: "users/children#update", as: "users_update_child"
    post "/users/sign_in_as/:id", to: "sessions#sign_in_as", as: "sign_in_as"

    get "/users/:id", to: "users#show", as: "user"
    put "/users/login(.format)", to: "sessions#new"
    put "/users" => "users#update", as: "update_user"

    get '/boundaries', to: 'users/boundaries#index', as: 'boundaries'
    put '/boundaries', to: 'users/boundaries#update', as: 'update_boundaries'

    get  '/users/potential_friends' => 'users/friend_request#index', as: 'potential_friends'
    get '/friend_request/:id' => 'users/friend_request#show', as: 'friend_request'
    post '/friend_request' => 'users/friend_request#create', as: 'create_friend_request'
    match '/friend_request/:id/accept' => 'users/friend_request#accept', as: 'accept_friend_request', via:[:put, :post]
    match '/friend_request/:id/decline' => 'users/friend_request#deny_request', as: 'deny_friend_request', via:[:put, :post]

    # Users APIs
    scope path: '/api/v1' do
      get '/users/followings', to: 'users#followings', as: 'api_get_followings'
      get '/videos/value_prop' => 'sessions#video', via: [:get]
      match '/users/logout' => 'sessions#destroy', via: [:get, :put, :delete], as: 'api_users_logout'

      get  '/users/potential_friends' => 'users/friend_request#index', as: 'api_get_potential_friends'
      post '/users/friend_request' => 'users/friend_request#create', as: 'api_create_friend_request'
      get '/users/friend_request/:id' => 'users/friend_request#show', as: 'api_show_friend_request'
      post '/users/friend_request/:id/accept' => 'users/friend_request#accept', as: 'api_accept_friend_request'
      post '/users/friend_request/:id/decline' => 'users/friend_request#deny_request', as: 'api_deny_friend_request'

      get 'users/me', to: 'users#me', as: 'api_show_current_user'
      get 'users/show_current_user', to: 'users#me'
      get 'users/dashboard', to: 'users#dashboard', as: 'api_users_dashboard'
      get 'users/:user_id/friends',    to: 'users#friends', as: 'api_specific_user_friends'
      get 'users/friends',    to: 'users#friends', as: 'api_users_friends'

      get 'users/children', to: 'users/children#index', as: 'api_users_children'
      get 'users/child', to: 'users/children#new', as: 'api_users_new_child'
      get 'users/child/:id', to: 'users/children#edit', as: 'api_users_edit_child'
      post 'users/child/create', to: 'users/children#create', as: 'api_users_create_child'
      post 'users/push_notifications', to: 'users/user_notification_tokens#create', as: 'api_create_user_notification_tokens'
      post 'users/child/login', to: 'users/children#login', as: 'api_users_login_child'
      put 'users/child/:id', to: 'users/children#update', as: 'api_users_update_child'
      post 'users/sign_in_as/:id', to: 'sessions#sign_in_as', as: 'api_sign_in_as'

      post 'users/children',   to: 'users/children#create'
      put  'users',            to: 'users#update'
      put  'users/child/:id',  to: 'users/children#update'

      get 'users/:id', to: 'users#show', as: 'api_user'

      get '/children/:child_id/dashboard/items', to: 'users/children#dashboard_parent', as: 'api_parent_child_dashboard'

      post 'users/:id/business_cards', to: 'users#business_cards', as: 'api_business_cards'
      get '/users/welcome/posting_info', to: 'categories#welcome_kids', as: 'welcome_kids_category'
    end

    scope path: '/api/v2' do
      get  '/users/potential_friends' => 'users/friend_request#index', as: 'api2_get_potential_friends'
      post '/users/friend_request' => 'users/friend_request#create', as: 'api2_create_friend_request'
      get '/users/friend_request/:id' => 'users/friend_request#show', as: 'api2_show_friend_request'
      post '/users/friend_request/:id/accept' => 'users/friend_request#accept', as: 'api2_accept_friend_request'
      post '/users/friend_request/:id/decline' => 'users/friend_request#deny_request', as: 'api2_deny_friend_request'
    end
  end

  scope path: '/api/v1' do

    resources :schools, path: '/schools'

    # Items APIs
    resources :item_comments
    post 'items/:id/decline', to: 'trades#decline'
    post 'items/:id/end', to: 'trades#destroy'

    match 'items/:id/favorite' => 'items#toggle_favorite_item', via: [:put, :post], as: 'api_toggle_favorite_item'
    post 'items', to: 'items#create'
    put 'items/:id/activate', to: 'manager#activate'
    put 'items/:id/deactivate', to: 'manager#deactivate'
    put 'items/:id', to: 'items#update'

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "landing"

  skip_before_filter :verify_auth_user
  skip_before_filter :load_account_data

  def home
    @version = params[:version].to_s.downcase
    template = 'home/home'

    render template: template, layout: 'landing_25'
  end

  def index
  	if auth_user
		  return redirect_to :users_dashboard
    else
	    #render :index
      return redirect_to new_user_session_path
    end
  end

  def terms
    @page_title_prefix = 'Terms of Service - '
  end

  def privacy
    @page_title_prefix = 'Privacy - '
  end

  def privacy_and_terms
    @page_title_prefix = 'Privacy and Terms of Service - '
  end

  def safety
    @page_title_prefix = 'Safety - '
    params[:hide_navbar] = true
    render layout: 'landing_25'
  end

  def about_us
    @page_title_prefix = 'About Us - '
    params[:hide_navbar] = true
    render layout: 'landing_25'
  end

  def faq
    @page_title_prefix = 'Frequently Asked Questions - '

    @question_answers = ::QuestionAnswer.order('order_index asc').to_a

    respond_to do|format|
      format.html do
        params[:hide_navbar] = true
        render layout: 'landing_25'
      end
      format.json { render json: @question_answers  }
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper

  HOW_IT_WORKS_VIDEO_ID_FOR_KID = 'VzNLpR7pbyk'
  HOW_IT_WORKS_VIDEO_URL_FOR_KID = 'https://www.youtube.com/embed/' + HOW_IT_WORKS_VIDEO_ID_FOR_KID + '?modestbranding=0&rel=0&showinfo=0'
  HOW_IT_WORKS_VIDEO_URL_FOR_KID_DIRECT = 'https://www.youtube.com/watch?v=' + HOW_IT_WORKS_VIDEO_ID_FOR_KID
  HOW_IT_WORKS_VIDEO_URL_FOR_PARENT = 'https://www.youtube-nocookie.com/embed/VLobm5PU22w?rel=0&showinfo=0'

  def how_it_works_video_iframe_for_kid
    content_tag(:iframe, { width:560, height:315, src: HOW_IT_WORKS_VIDEO_URL_FOR_KID,
      frameborder:0, 'allowfullscreen'=> true} ) { }
  end

  def how_it_works_video_iframe_for_parent
    content_tag(:iframe, { width:560, height:315, src: HOW_IT_WORKS_VIDEO_URL_FOR_PARENT,
                           frameborder:0, 'allowfullscreen'=> true} ) { }
  end
end

app/views/home/_bottom_tabbar.html.haml
- content_for(:head_extra) do

  :css
    body {
      padding-bottom: 100px;
    }

    .tab-link {
      width: 100px;
      height: 100px;
    }
    .tab-browse { background: url('/assets/nav/tabbar-browse@2x.png') no-repeat center; }
    .tab-post { background: url('/assets/nav/tabbar-post@2x.png') no-repeat center; }
    .tab-friends { background: url('/assets/nav/tabbar-friends@2x.png') no-repeat center; }
    .tab-likes { background: url('/assets/nav/tabbar-likes@2x.png') no-repeat center; }
    .tab-trading { background: url('/assets/nav/tabbar-trading@2x.png') no-repeat center; }

    @media only screen and (max-width: 600px)  {
      .tab-link {
        width: 50px;
        height: 50px;
      }
      .tab-browse { background: url('/assets/nav/tabbar-browse.png') no-repeat center; }
      .tab-post { background: url('/assets/nav/tabbar-post.png') no-repeat center; }
      .tab-friends { background: url('/assets/nav/tabbar-friends.png') no-repeat center; }
      .tab-likes { background: url('/assets/nav/tabbar-likes.png') no-repeat center; }
      .tab-trading { background: url('/assets/nav/tabbar-trading.png') no-repeat center; }
    }


%nav(class="navbar navbar-default navbar-fixed-bottom" style='background-color:white; z-index:6000;')
  %div(class='container content-width')
    %table(style='width: 100%')
      %tbody
        %tr
          %td.text-center
            %a(class='tab-link' href="#{newest_items_path}" title="Browse Items")
              %img(src="/assets/nav/tabbar-browse@2x.png" alt="Browse Items")
          %td.text-center
            %a(class='tab-link' href="#{new_item_path}" title="Post Item")
              %img(src="/assets/nav/tabbar-post@2x.png" alt="Post Item")
          %td.text-center
            %a(class='tab-link' href="#{friends_items_path}" title="Friends")
              %img(src="/assets/nav/tabbar-friends#{params[:action].to_s=='friends' ? '-selected' : ''}@2x.png" alt="Friends")
          %td.text-center
            %a(class='tab-link' href="#{likes_items_path}" title="Your Likes")
              %img(src="/assets/nav/tabbar-likes#{params[:action].to_s=='likes' ? '-heart-red' : ''}@2x.png" alt="Your Likes")
          %td.text-center
            %a(class='tab-link' href="#{trades_path}" title="Your Trades")
              %img(src="/assets/nav/tabbar-trading#{params[:controller].to_s=='trading/trades' ? '-selected' : ''}@2x.png" alt="Your Trades")

app/views/home/about_us.html.erb
<% content_for(:head_extra) do %>
  <style type="text/css">
    #top-intro {
      margin-top:-78px;
      padding: 50px 0;
    }
    .intro-title p {
      font-size: 1.4em;
      font-weight: 200;
      padding: 10px 0;
    }

    /* Smallest */
    @media only screen and ( max-width: 400px )
    {
      #top-intro {
        margin-top:-92px;
        padding: 0 0 25px 0;
      }
      .intro-title p {
        font-size: 1.2em;
        line-height: 20px;
      }
    }
    /* Small */
    @media only screen and ( min-width: 400px) and ( max-width: 640px )
    {

      #top-intro {
        margin-top:-92px;
        padding: 0 0 25px 0;
      }
      #banner-destop h1 {
        font-size: 20pt;
        line-height: 40px;
      }
      .intro-title p {
      }
    }
    /* Medium */
    @media only screen and ( min-width: 640px) and (max-width: 800px )
    {
      #top-intro {
        margin-top:-54px;
        padding: 0 0 50px 0;
      }
      .intro-title p {
        font-size: 20pt;
      }
    }
    /* Big */
    @media only screen and ( min-width: 800px )
    {
      .intro-title p {
        font-size: 28pt;
        line-height: 1.4em;
      }
    }
  </style>

<% end # head_extra %>

<% content_for(:footer_extra) do %>
  <script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>

  <%= render partial: 'layouts/google_analysis' %>
<% end # footer_extra %>

<header class="header-about" ><!--header-->
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-sm-6 col-xs-4">
        <div id="logo-destop"><a href="/"><img src="/assets/landing-25/about-logo.png" alt="logo" /></a></div>
      </div>
      <div class="col-md-6 col-sm-6 col-xs-8">
        <% if user_signed_in? -%>
          <a href="<%= users_logout_path -%>" class="about-login btn-default">LOG OUT</a>
        <% elsif request.path != new_user_session_path -%>
          <a href="<%= new_user_session_path %>" class="about-login btn-default">LOGIN</a>
        <% else -%> &nbsp;
        <% end -%>
      </div>
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="banner-text">
          <p class="cust-text">&#34;Isabelle will make me the happiest girl in the world.&#34;</p>
        </div>
      </div>
    </div><!--row-->
  </div><!--container end-->
</header>

<section class="section1"><!--section1-->
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <p class="para1"> With that promise, I braved the December chill, took a train into NYC, hopped in a
          cab and stood in line at the American Girl store. Two hours later and &#36;100&#43; poorer,
          Isabelle had a new loving home.</p>
        <p class="para2">Fast forward three months. We all know, the love for a toy is... fickle.</p>
        <p class="para3">Surely, there must be another child ready to be</p>
        <p class="para4"> &#34;the happiest girl in the world&#34;.</p>
        <p class="para5"> And so KidsTrade came to be.</p>
      </div>
    </div>
  </div>
</section><!--section1 end-->

<section class="section2"><!--section2-->
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <p class="para1">About Us</p>
        <p class="para2">
          We are a Princeton-based start-up founded and run by parents
          committed to creating entertaining and educational apps for kids. Our
          entrepreneurial team has a combined 100 years of experience in the
          fields of technology, entertainment, online security, marketing, graphic
          design, computer programming and product development. We love
          what we do and, more importantly, we think you and your kids will love it!
        </p>
      </div>
    </div>
  </div>
</section><!--section2 end-->

<section class="section3">	<!--section3-->
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <ul class="apple-logo">
          <li><a href="https://itunes.apple.com/app/id1042828368"><img src="/assets/landing-25/apple-logo1.png" alt="IOS App"></a></li>
          <li><a href="https://play.google.com/store/apps/details?id=com.cubbyshop.cubbyshop"><img src="/assets/landing-25/google-play-live.png" alt="Google Play App"></a></li>
        </ul>
      </div>
    </div>
  </div>
</section><!--section3 end-->

<%= render partial: 'layouts/landing_footer' %>

app/views/home/faq.html.erb
<% content_for(:footer_extra) do %>
  <%= render partial: 'layouts/google_analysis' %>
<% end # footer_extra %>
<% if !params[:minimal] -%>
<header class="header-faq" ><!--header-->
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-sm-6 col-xs-6">
        <div id="logo-destop"><a href="/"><img src="/assets/landing-25/logo-desktop.png" alt="logo" /></a></div>
      </div>
      <div class="col-md-6 col-sm-6 col-xs-6">
        <% if user_signed_in? -%>
          <a href="<%= users_logout_path -%>" class="faq-login btn-default">LOG OUT</a>
        <% elsif request.path != new_user_session_path -%>
          <a href="<%= new_user_session_path %>" class="faq-login btn-default">LOGIN</a>
        <% else -%> &nbsp;
        <% end -%>
      </div>

    </div><!--row-->
  </div><!--container end-->
</header>
<% end # header -%>
<section class="section1 faq-section1"><!--section1-->
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <p class="faq-para1"> Frequently Asked Questions</p>
        <ul class="faq-list">
          <% @question_answers.each do|qa| %>
            <li>
              <div class="faq-content">
                <div class="faq-section">
                  <a class="faq-section-title answer-link" href="#"><%= qa.question %></a>
                  <div class="faq-section-content">
                    <%= answer_to_html(qa.answer).html_safe -%>
                  </div>
                </div>
              </div>
            </li>
          <% end -%>
        </ul>
      </div>
    </div>
  </div>
</section><!--section1 end-->
<% if !params[:minimal] -%>
<section class="section3">	<!--section3-->
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <ul class="apple-logo">
          <li><a href="https://itunes.apple.com/app/id1042828368"><img src="/assets/landing-25/apple-logo1.png" alt="IOS App"></a></li>
          <li><a href="https://play.google.com/store/apps/details?id=com.cubbyshop.cubbyshop"><img src="/assets/landing-25/google-play-live.png" alt="Google Play App"></a></li>
        </ul>
      </div>
    </div>
  </div>
</section><!--section3 end-->

<%= render partial: 'layouts/landing_footer' %>
<% end # footer -%>
<!-- footer -->

app/views/home/safety.html.erb
<% content_for(:footer_extra) do -%>
  <%= render partial: 'layouts/google_analysis' -%>
<% end # footer_extra -%>

<header class="header-safty" ><!--header-->
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-sm-6 col-xs-4">
        <div id="logo-destop"><a href="/"><img src="/assets/landing-25/about-logo.png" alt="logo" /></a></div>
      </div>
      <div class="col-md-6 col-sm-6 col-xs-8">
        <% if user_signed_in? -%>
          <a href="<%= users_logout_path -%>" class="about-login btn-default">LOG OUT</a>
        <% elsif request.path != new_user_session_path -%>
          <a href="<%= new_user_session_path %>" class="about-login btn-default">LOGIN</a>
        <% else -%> &nbsp;
        <% end -%>
      </div>
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="banner-text">
          <p class="cust-text"></p>
        </div>
      </div>
    </div><!--row-->
  </div><!--container end-->
</header>
<div class="clearfix"></div>
<section class="safety-page">
  <div class="saftey-top">
    <div class="container">
      <div class="row">
        <div class="col-md-12  col-sm-12  col-xs-12 col-xs-offset-0">
          <div class="saftey-top1">
            <h1>Safety Is Priority One</h1><!-- top heading -->
            <h2>We’re Parents, too.</h2><!-- top heading two-->
            <p>KidsTrade is founded and run by  parents. So, your
              concerns are our  concerns. From sophisticated algorithmic
              filters that snag swear words to live people with years of
              online security experience using  their eyes and their
              instincts, we employ an array of methods to  ensure a safe
              environment.
            </p><!-- top para -->
          </div>
        </div>
        <div class="col-md-12  col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0">
          <div class="safteypage-list">
            <div class="row">
              <div class="saftey-list-li">
                <div class="col-md-2 col-sm-3 col-xs-12">
                  <div class="safteypage-img">
                    <img src="/assets/landing-25/saftey1.png" alt="" />
                  </div>
                </div>
                <div class="col-md-10 col-sm-9 col-xs-12">
                  <div class="safteypage-textarea">
                    <h3>BOUNDARIES</h3>
                    <p>
                      Kids are only linked to friends and other students at their school.
                      So, a familiar face is always at the other end of a trade.
                    </p>
                  </div>
                </div>
              </div><!-- list one -->
              <div class="saftey-list-li">
                <div class="col-md-2 col-sm-3 col-xs-12">
                  <div class="safteypage-img">
                    <img src="/assets/landing-25/saftey3.png" alt="" />
                  </div>
                </div>
                <div class="col-md-10 col-sm-9 col-xs-12">
                  <div class="safteypage-textarea">
                    <h3>NOTIFICATIONS</h3>
                    <p>
                      When a parent creates an account, they are directly notified when their
                      child posts an item, agrees to an uneven trade, or wishes to buy or sell.
                      Parents can log in anytime to view activity.
                    </p>
                  </div>
                </div>
              </div><!-- list three -->
              <div class="saftey-list-li safty-list">
                <div class="col-md-2 col-sm-3 col-xs-12">
                  <div class="safteypage-img">
                    <img src="/assets/landing-25/saftey4.png" alt="" />
                  </div>
                </div>
                <div class="col-md-10 col-sm-9 col-xs-12">
                  <div class="safteypage-textarea">
                    <h3>FILTERS</h3>
                    <p>
                      An exhaustive list of red-flagged words
                      means offensive posts won’t see the light
                      of day.
                    </p>
                  </div>
                </div>
              </div><!-- list four -->
              <div class="saftey-list-li safty-list">
                <div class="col-md-2 col-sm-3 col-xs-12">
                  <div class="safteypage-img">
                    <img src="/assets/landing-25/saftey5.png" alt="" />
                  </div>
                </div>
                <div class="col-md-10 col-sm-9 col-xs-12">
                  <div class="safteypage-textarea">
                    <h3>REPORT</h3>
                    <p>
                      Both kids and parents can report any
                      activity or item they feel is inappropriate
                      and it is immediately removed.
                    </p>
                  </div>
                </div>
              </div><!-- list five -->
              <div class="saftey-list-li safty-list">
                <div class="col-md-2 col-sm-3 col-xs-12">
                  <div class="safteypage-img">
                    <img src="/assets/landing-25/saftey6.png" alt="" />
                  </div>
                </div>
                <div class="col-md-10 col-sm-9 col-xs-12">
                  <div class="safteypage-textarea">
                    <h3>BLOCK</h3>
                    <p>
                      Parents can block specific users, keywords
                      and even entire  categories.  These
                      restrictions can be customized for each
                      child.
                    </p>
                  </div>
                </div>
              </div><!-- list six -->

            </div><!--row-->

          </div><!--safty list-->

        </div> <!-- col end -->

      </div>


    </div><!--container-->
  </div><!--made-app-->
  <section class="section3 safty-mac">	<!--section3-->
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <ul class="apple-logo">
            <li><a href="http://itunes.apple.com/app/id1042828368"><img src="/assets/landing-25/apple-logo1.png" alt="IOS App"></a></li>
            <li><a href="https://play.google.com/store/apps/details?id=com.cubbyshop.cubbyshop"><img src="/assets/landing-25/google-play-live.png" alt="Google Play App"></a></li>
          </ul>
        </div>
      </div>
    </div>
  </section><!--section3 end-->
</section>

<%= render partial: 'layouts/landing_footer' %>