config/routes.rb
KidsToys::Application.routes.draw do



  use_doorkeeper

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match 'admin' => 'users/admin#index', :via => :get, :as => 'admin'
  match 'admin' => 'users/admin#login', :via => :post, :as => 'admin_login'
  match 'admin/users' => 'users/admin#users', :via => :get, :as => 'admin_users'
  match 'admin/update_user/:id' => 'users/admin#update_user', :via => [:put, :post], :as => 'admin_update_user'
  match 'admin/delete_user/:id' => 'users/admin#delete_user', :via => [:delete], :as => 'admin_delete_user'
  match 'admin/schools' => 'users/admin#schools', :via => :get, :as => 'admin_schools'
  match 'admin/notifications' => 'users/admin#notifications', :via => :get, :as => 'admin_notifications'
  match 'admin/logout' => 'users/admin#logout', :via => [:get, :delete], :as => 'admin_logout'

  match 'question_answers/update_all' => 'question_answers#update_all', via: [:put, :post], as: 'update_all_question_answers'
  resources :question_answers, except:[:show]

  resources :item_comments

  resources :cart_items, module: 'carts'

  match 'schools/admin' => 'schools#admin', :via => :get, :as => :schools_admin
  match 'schools/admin/:id' => 'schools#admin_edit', :via => :get, :as =>  :schools_admin_edit
  match 'schools/admin/:id' => 'schools#admin_update', :via => :post, :as => :schools_admin_update
  match 'schools/admin/:id' => 'schools#admin_destroy', :via=> :delete, :as => :schools_admin_destroy
  resources :schools, path: '/schools'

  match '/demo' => 'items#demo'

  namespace :inventory do
    resources :manager, :only => [:index] do

    end
    match 'activate' => 'manager#activate', as: 'activate_item'
    match 'approve' => 'manager#approve', as: 'approve_item'
    match 'deactivate' => 'manager#deactivate', as: 'deactivate_item'
    match 'decline' => 'manager#decline', as: 'decline_item'

    match 'item_for_approval' => 'manager#item_for_approval_notice', as: 'item_for_approval_notice'
  end


  match 'admin/categories' => 'categories#admin', :as => :admin_categories
  match 'categories/update_all' => 'categories#update_all', as: :update_all_categories, via:[:put, :post]
  resources :categories

  match 'category_groups/update_all' => 'category_groups#update_all', as: :update_all_category_groups, via:[:put, :post]
  match 'category_groups/:id/add_mapping' => 'category_groups#add_mapping', as: :add_category_group_mapping, via:[:put, :post]
  match 'category_groups/:id/add_curated_category' => 'category_groups#add_curated_category', as: :add_curated_category, via:[:put, :post]
  resources :category_groups
  resources :category_group_mappings, only: [:edit, :update]

  match 'categories/:id(/:title)' => 'categories#show', :as => :category_title
  match 'user_categories' => 'categories#user_categories', :as => :user_categories

  get 'account/confirm' => 'account_confirmation#index', as: :account_confirmation
  get 'account/credit_card' => 'account_confirmation#credit_card', as: :account_credit_card
  get 'account/driver_license' => 'account_confirmation#driver_license', as: :account_driver_license
  post 'account/driver_license' => 'account_confirmation#upload_driver_license', as: :account_upload_driver_license
  post 'account/confirm/payment' => 'account_confirmation#authorize_payment', as: :account_confirmation_payment
  get 'account/confirmed' => 'account_confirmation#account_confirmed', as: :account_confirmed
  #####################
  # Trade

  resources :trades, module: 'trading', except: [:edit, :update, :create], as: 'trade'
  match 'trades/(:id)(.:format)' => 'trading/trades#create', as: 'create_trade', via: :post
  match 'trades/(:id)(.:format)' => 'trading/trades#reply', as: 'reply_trade', via: :put
  match 'trades/:id/comments(.:format)' => 'trading/trades#list_comments', as: 'trade_comments', via: :get
  match 'trades/:id/comments(.:format)' => 'trading/trades#comments', as: 'create_trade_comments', via: :post
  match 'trades/:id/accept(.:format)' => 'trading/trades#accept', as: 'accept_trade', via: :post
  match 'trades/:id/decline(.:format)' => 'trading/trades#decline', as: 'decline_trade', via: :delete
  match 'trades/:id/cancel(.:format)' => 'trading/trades#destroy', as: 'cancel_trade', via: [:put, :post, :delete]
  match 'trades/:id/pick_meeting(.:format)' => 'trading/trades#pick_meeting', as: 'pick_meeting', via: [:put, :post]
  match 'trades/:id/respond_to_meeting(.:format)' => 'trading/trades#respond_to_meeting', as: 'respond_to_meeting', via: [:put, :post]
  match 'trades/:id/confirm(.:format)' => 'trading/trades#confirm_completion', as: 'confirm_completion', via: [:put, :post]
  match 'trades/:id/pack(.:format)' => 'trading/trades#confirm_packed', as: 'confirm_packed', via: [:put, :post]
  match 'trades/:id/completed(.:format)' => 'trading/trades#completed', as: 'completed_change', via: [:put, :post]

  resources :buy_requests, module: 'trading', only: [:new, :create, :show]
  match 'buy_requests/(:id)/accept(.:format)' => 'trading/buy_requests#accept', as: 'accept_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/decline(.:format)' => 'trading/buy_requests#decline', as: 'decline_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/confirm(.:format)' => 'trading/buy_requests#confirm', as: 'confirm_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/sold(.:format)' => 'trading/buy_requests#sold', as: 'sold_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/not_sold(.:format)' => 'trading/buy_requests#not_sold', as: 'not_sold_buy_request', via: [:put, :post]

  #####################
  # Notifications

  resources :notifications, module: 'users', only: [:index, :show] do
    member do
      delete 'delete'
    end
  end
  match 'notifications/archive' => 'users/notifications#archive', as: 'archive_notifications', via: :put
  match '/notifications/push' => 'users/notifications#send_push_notification', as: 'send_push_notification', via: [:put, :post]
  match '/notifications_count(.:format)' => 'users/notifications#count', as: 'notifications_count', via: :get

  root :to => 'home#home'
  get "/home/:version" => "home#home"
  get "/terms" => "home#terms"
  get "/privacy" => "home#privacy"
  get "/privacy_and_terms" => "home#privacy_and_terms"
  get "/safety" => "home#safety"
  get "/about_us" => "home#about_us"
  get "/faq" => "home#faq"

  match 'tips/update_all' => 'tips#update_all', via: [:put, :post], as: 'update_all_tips'
  resources :tips, except: [:show]

  #####################
  # User

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {registrations: 'users', sessions: 'sessions', passwords: 'passwords'}
  devise_scope :user do
    post '/forgot_password', to: 'passwords#create'
    get '/users/password/edit', to: 'password#edit'
    put '/users/password', to: 'passwords#update'
  end
  #post '/forgot_password' => 'devise/passwords#create'
  #get '/forgot_password'=> 'devise/passwords#edit'

  # Custom routes that still use :users scope
  devise_scope :user do
    get "/users/logout" => "sessions#destroy"
    get "/users/show_current_user", as: "show_current_user"
    get "/users/dashboard", to: "users#dashboard", as: "users_dashboard"
    get "/users/friends", to: "users#friends", as: "users_friends"
    get "/users/:id/items", to: "stores#show", as: "users_items"

    get "/users/children", to: "users/children#index", as: "users_children"
    get "/users/child", to: "users/children#new", as: "users_new_child"
    match '/users/child/:id/school' => 'users/children#school', as: 'child_school', via:[:get]
    match '/users/child/:id/update_school' => 'users/children#update_school', as: 'child_update_school', via:[:put, :post]
    get "/users/child/:id", to: "users/children#edit", as: "users_edit_child"
    post "/users/child/create", to: "users/children#create", as: "users_create_child"
    post '/users/student/create', to: 'users/children#create_student', as: 'users_create_student'
    post "/users/push_notifications", to: "users/user_notification_tokens#create", as: "create_user_notification_tokens"
    post "/users/child/login", to: "users/children#login", as: "users_login_child"
    put "/users/child/:id", to: "users/children#update", as: "users_update_child"
    post "/users/sign_in_as/:id", to: "sessions#sign_in_as", as: "sign_in_as"

    get "/users/:id", to: "users#show", as: "user"
    put "/users/login(.format)", to: "sessions#new"
    put "/users" => "users#update", as: "update_user"

    get '/boundaries', to: 'users/boundaries#index', as: 'boundaries'
    put '/boundaries', to: 'users/boundaries#update', as: 'update_boundaries'

    get  '/users/potential_friends' => 'users/friend_request#index', as: 'potential_friends'
    get '/friend_request/:id' => 'users/friend_request#show', as: 'friend_request'
    post '/friend_request' => 'users/friend_request#create', as: 'create_friend_request'
    match '/friend_request/:id/accept' => 'users/friend_request#accept', as: 'accept_friend_request', via:[:put, :post]
    match '/friend_request/:id/decline' => 'users/friend_request#deny_request', as: 'deny_friend_request', via:[:put, :post]

    # Users APIs
    scope path: '/api/v1' do
      get '/users/followings', to: 'users#followings', as: 'api_get_followings'
      get '/videos/value_prop' => 'sessions#video', via: [:get]
      match '/users/logout' => 'sessions#destroy', via: [:get, :put, :delete], as: 'api_users_logout'

      get  '/users/potential_friends' => 'users/friend_request#index', as: 'api_get_potential_friends'
      post '/users/friend_request' => 'users/friend_request#create', as: 'api_create_friend_request'
      get '/users/friend_request/:id' => 'users/friend_request#show', as: 'api_show_friend_request'
      post '/users/friend_request/:id/accept' => 'users/friend_request#accept', as: 'api_accept_friend_request'

app/helpers/categories_helper.rb
module CategoriesHelper

  BG_COLORS = {
    'no-color' => '',
    'dark-red'=>[204,0,0], 'light-red'=>[255,31,71], 'dark-blue'=>[19,128,218], 'light-blue'=>[64,159,236],
    'dark-green'=>[102,153,0], 'light-green'=>[153,204,0], 'dark-yellow'=>[255,153,0], 'light-yellow'=>[248,200,5],
    'dark-pink'=>[255,62,166], 'light-pink'=>[252,188,205], 'light-violet'=>[170,102,204], 'lego-tile'=>[250,7,1]
  }

  BG_COLOR_CLASSES = %w|dark-red-bg light-red-bg dark-blue-bg light-blue-bg dark-green-bg light-green-bg dark-yellow-bg light-pink-bg dark-pink-bg light-violet-bg lego-tile-bg|

  ##
  # +view_component_id+ The ID of the view object that should have background changed to chosen color.
  # +input_field_id+ The ID of the input field where the chosen color value can be stored.
  def make_bg_color_dropdown_menu_for(input_field_id, view_component_id)
    content_tag(:ul, { role: 'menu', class: 'dropdown-menu', fieldid: input_field_id, viewid: view_component_id } ) do
      BG_COLORS.keys.collect do|bgcolor|
        color_hex = BG_COLORS[bgcolor].is_a?(String) ? BG_COLORS[bgcolor] : '#' + BG_COLORS[bgcolor].collect{|color_i| color_i.to_full_hex }.join
        content_tag(:li, style: "background-color: #{color_hex}") do
          link_to(bgcolor.gsub(/\-bg/i, '').humanize, 'javascript:void(0)', bgcolor: color_hex )
        end
      end.join("\n").html_safe
    end.html_safe
  end

  ADD_PICTURE_IMAGE = '/assets/icons/add@2x.png'

  ##
  # +category+ <Category>
  # +which_picture+ <String> the Category picture name attribute
  # +image_alt+ <String> The tip for the image tag
  def make_category_picture_place_holder(category, which_picture, image_alt = 'Category Icon')
=begin

              = image_tag(category.male_icon_url.present? ? category.male_icon_url : add_image, id:"male_icon_img", alt: "Category Icon for Boys")
              = f.file_field(:male_icon)
=end
    picture_path = category.send( "#{which_picture}_url".to_sym ) # .attributes won't work because these some_icon_url are only generated methods
    image_tag(picture_path.present? ? picture_path : ADD_PICTURE_IMAGE, id:"#{which_picture}_img", class:'vertical-center', alt: image_alt).html_safe
  end

  ##
  # First check current_user's gender.  But if current_user, checks whether category is for female ONLY.
  # @return <Boolean> whether gender should be female
  def is_female_for_category?(category, current_user = nil)
    is_female = false
    if current_user
      is_female = current_user.female?
    else
      is_female = !category.for_male? && category.for_female?
    end
    is_female
  end

  def category_bg_color_for(category, current_user = nil)
    is_female = is_female_for_category?(category, current_user)
    bg_color = is_female ? category.female_icon_background_color : category.male_icon_background_color
    bg_color = '#cccccc' if bg_color.blank?
    bg_color
  end

  ##
  # return <String> may be nil or blank
  def category_icon_url_for(category, current_user = nil)
    is_female = is_female_for_category?(category, current_user)
    icon_url = is_female ? category.female_icon_url : category.male_icon_url
    icon_url = '' if icon_url.to_s == '/assets/'
    icon_url
  end

  def hide_name_for(category, current_user = nil)
    is_female = is_female_for_category?(category, current_user)
    is_female ? category.female_hides_name : category.male_hides_name
  end

  ##
  # ==== Arguments
  #   category <Category>
  #   current_user <User> optional; for determining gender-specific attributes like background color or icon.
  #   options <Hash>
  #     :class - additional CSS class for the outside wrapper of the cell
  #     :url - instead of items_search_category_path
  def make_category_cell(category, current_user = nil, options = {} )
    tag_name = options.delete(:tag_name) || :div
    options[:class] ||= 'category-cell'
    bg_color = category_bg_color_for(category, current_user)
    icon_url = category_icon_url_for(category, current_user)
    hide_name = hide_name_for(category, current_user)

    #options[:style] = "background: url('#{icon_url}') center center no-repeat #{bg_color};"
    options[:style] = "background-color: #{bg_color};"
    url = options[:url] || items_search_category_path(category_id: category.id)
    is_remote = options.delete(:remote) || false

    content_tag(tag_name, options) do
      content_tag(:div, class: (hide_name ? 'category-cell-full-icon vertical-center' : 'category-cell-icon' ) ) do
        icon_tag = ''
        if icon_url.present?
          icon_tag = link_to(url, remote: is_remote){ image_tag(icon_url, alt:'') }
        end
        icon_tag
      end +
      content_tag(:div, class: (hide_name ? '' : "category-cell-label#{category.name.length > 9 ? ' category-cell-label-small' : ''}") ) do
        hide_name ? '' : link_to(category.name, url )
      end
    end
  end
  
  # Part of the category-based posting.
  def sample_category_photo(category)
    gender_suffix = ''
    if category.for_male? && !category.for_female?
      gender_suffix = '_male'
    elsif !category.for_male? && category.for_female?
      gender_suffix = '_female'
    end
    url = category.camera_background_for(current_user)
    url.blank? ? "/assets/items/item_photos/category_photo_#{category.id}#{gender_suffix}.png" : url 
  end

end

app/views/categories/_form.html.haml
- ## 
- # Required locals:
- #   category <Category>
- add_image = '/assets/icons/add@2x.png'

= form_for(category, remote: !category.new_record?, html: { id: "category_#{category.id}"} ) do|f|
  = f.hidden_field :male_icon_background_color, id: "male_icon_bg_color_#{category.id}"
  = f.hidden_field :female_icon_background_color, id: "female_icon_bg_color_#{category.id}"
  = f.hidden_field :male_index, id: "male_index_#{category.id}"
  = f.hidden_field :female_index, id: "female_index_#{category.id}"
  %div(class='pull-left')
    = f.text_field(:name, class: 'form-control', placeholder: 'Category Name')
    %br
    = f.text_field(:icon_label, class: 'form-control', placeholder: 'Category Label on Icon')
    %br
      - if category.new_record?
        = f.submit('Create New Category', class: 'btn btn-lg btn-success', :disable_with => "Submitting...")
      - else
        = f.submit('Save Category', class: 'btn btn-lg btn-primary', :disable_with => "Submitting...")
        = link_to(category_path(id: category.id), method:'delete', remote: true, style:"margin:10px;", class:'btn btn-default', confirm:"Sure to delete this category?") do
          %span.glyphicon.glyphicon-remove.warning-color/

  %div(class='pull-right' style="display: inline-block;")
    %table(class='gray-border-color')
      %tbody
        %tr
          %td.text-center
            = f.check_box(:male_index, { checked: category.for_male?, 'data-toggle'=>"tooltip", 'data-placement'=>"right", 'title'=>"Click to toggle whether category is For Boys" }, category.selected_male_index)
            %br
            = f.check_box(:male_hides_name, { 'data-toggle'=>"tooltip", 'data-placement'=>"right", 'title'=>"Click to toggle whether category name should be hidden" } )
            = f.label(:male_hides_name, 'Hide name?', class: 'small-size-text')

          %td.category-icon-placeholder(id="male_icon_cell_#{category.id}" style="background-color:#{category.male_icon_background_color.to_s}")
            .btn-group
              %button(type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false")
                Icon:
                %span.caret
              = make_bg_color_dropdown_menu_for("male_icon_bg_color_#{category.id}", "male_icon_cell_#{category.id}")
            %br
              = make_category_picture_place_holder( category, :male_icon, "Category Icon for Boys" )
              = f.file_field(:male_icon)
          %td.category-icon-placeholder(id="male_camera_bg_cell_#{category.id}")
            %label Camera BG:
            %br
              = make_category_picture_place_holder( category, :male_camera_background, "Category Camera Background for Boys" )
              = f.file_field(:male_camera_background)
        %tr
          %td.text-center
            = f.check_box(:female_index, { checked: category.for_female?, 'data-toggle'=>"tooltip", 'data-placement'=>"bottom", 'title'=>"Click to toggle whether category is For Girls" }, category.selected_female_index)
            %br
            = f.check_box(:female_hides_name, { 'data-toggle'=>"tooltip", 'data-placement'=>"right", 'title'=>"Click to toggle whether category name should be hidden" } )
            = f.label(:female_hides_name, 'Hide name?', class: 'small-size-text')
          %td.category-icon-placeholder(id="female_icon_cell_#{category.id}" style="background-color:#{category.female_icon_background_color.to_s}")
            .btn-group
              %button(type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false")
                Icon:
                %span.caret
              = make_bg_color_dropdown_menu_for("female_icon_bg_color_#{category.id}", "female_icon_cell_#{category.id}")

            %br
              = make_category_picture_place_holder( category, :female_icon, "Category Icon for Girls" )
              = f.file_field(:female_icon)
          %td.category-icon-placeholder(id="female_camera_bg_cell_#{category.id}")
            %label Camera BG:
            %br
              = make_category_picture_place_holder( category, :female_camera_background, "Category Camera Background for Girls" )
              = f.file_field(:female_camera_background)

app/views/categories/admin.html.haml
- all_cats = ::Category.order('name asc').all
- content_for(:head_extra) do

  :css
    .button-success { background-color:#c4e3ff; padding:0; }
    .button-changed { background-color:#ffddf0; padding:0; }
    .category-group-input { font-size:1.1em; }
    .category-group-wrapper {
      margin: 1% 2%;
      display: inline-block;
      width: 480px;
      vertical-align: top;
    }
    .category-group-wrapper input[type=text] { width:50px; text-align: center; }
    .category-group-box {
      border: solid 5px #999999;
      margin: 10px 0 16px 0;
      padding: 5px;
    }
    .category-group-box-male { border-color: rgb(64, 159, 237); }
    .category-group-box-female { border-color: rgb(255, 31, 71); }
    .category-tiles-list { list-style-type:none; padding-left:0; margin-left:0; }

    @media only screen and (max-width: 640px) {
      .category-group-wrapper { width: 360px; }
    }

- content_for(:footer_extra) do
  :javascript

    $(function() {

      $(".category-group-input").change( function(){
        var cgid = $(this).attr("data");
        var cgsubmit = $("#save_category_group_" + cgid);
        cgsubmit.removeClass("button-success");
        cgsubmit.addClass("button-changed");
      });
      $(".category-tiles-list").sortable({
        update: function(event, ui) {
          var children = $(this).children();
          var order = 1;
          for (var ci = 0; ci < children.length; ci++) {
            if (children[ci].tagName == "LI")
            {
              var id = $(children[ci]).attr("data");
              $("#curated_category_" + id +"_order_index").val(order);
              order++;
            }
          }
          var cgid = $(this).attr("data");
          $("#update_all_form_" + cgid).submit();
        }
      }).disableSelection();
      $("input[data-disable-with]").click( function(){ $(this).attr('disabled',true); $(this).val($(this).attr('data-disable-with')); } );
      $('[data-toggle="tooltip"]').tooltip();
    });


.container
  .row.form-group.clearfix(style="vertical-align:bottom; margin:0;")
    %img.pull-left(src="/assets/logos/kidstrade-title.png" alt="KIDSTrade" style="margin:0 2% 0 0;")
    %p.pull-left.normal-weight.text-medium-title(style="margin:0 2% 0 0;")
      %a(href='/admin') ADMIN
      %span.gray-title-color - CATEGORY GROUPS
    %p.pull-right(style="width:25%;")
      -#= submit_tag("SUBMIT", class:'btn btn-large light-blue-bg', disable_with:'Submitting...')
.section-gap
%hr.full-separator
.container
  - @category_groups.each do|cg|
    %div(style="display:inline-block;")
      .category-group-wrapper.form-inline
        = form_for(cg, method: :put, remote:true, id:"category_group_form_#{cg.id}") do|f|
          .form-group.moderate-dark-title-color(style='width:100%;')
            = f.text_field(:name, class:"category-group-input form-control #{cg.gender.downcase}-color", style:'width:240px; font-size:1.4em; font-weight:500;', data:"#{cg.id}")
            = f.text_field(:lowest_age, class:'category-group-input form-control', data:"#{cg.id}")
            to
            = f.text_field(:highest_age, class:'category-group-input form-control', data:"#{cg.id}")
            %button(type='submit' class='btn button-success glyphicon glyphicon-floppy-disk pull-right' id="save_category_group_#{cg.id}" title='Save changes to this Category Group' style='padding:10px;')/
        = form_tag(update_all_category_groups_path, method: :put, remote:false, id:"update_all_form_#{cg.id}") do
          %div(class="category-group-box category-group-box-#{cg.gender.downcase}")
            %ul.category-tiles-list(id="category_group_#{cg.id}" data="#{cg.id}")
              - cg.category_group_mappings.order("order_index asc").each_with_index do|mapping, index|
                %input(type='hidden' name="mapping_#{mapping.id}[order_index]" id="mapping_#{mapping.id}_order_index" value="#{index}")/
                = make_category_cell(mapping.mapped_category, cg.sample_child, url: edit_category_group_mapping_path(mapping), class:'category-cell', tag_name: :li, name: mapping.category.name.underscore, data: mapping.id, 'data-toggle'=>"tooltip", 'data-placement'=>"right", 'title'=>"Click to modify #{mapping.category.name}.  \nDrag to re-order." )
                = link_to(' ', edit_category_group_mapping_path(mapping) )
            .clearfix
          .dropdown
            %button.btn.btn-large.btn-default(id="add_category_btn_#{cg.id}" type='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded="false"  style="width:94%;")
              ADD CATEGORY
              %span.caret
            %ul.dropdown-menu.list-group(aria-labelledby="add_category_btn_#{cg.id}" )
              - category_group_cat_ids = cg.curated_categories.collect(&:category_id)
              - all_cats.each do|cat|
                - unless category_group_cat_ids.include?(cat.id)
                  %li.list-group-item
                    = link_to(cat.name, add_category_group_mapping_path(id: cg.id, mapping:{category_id: cat.id} ), remote:true, method:'post', style:"text-align:left;")

  #category_group_mapping_modal.modal.fade(tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true")
    .modal-dialog(role="document")
      .modal-content
        .modal-header
          %button.close(type="button" data-dismiss="modal" aria-label="Close")
            %span(aria-hidden="true") &times;
          %h4.modal-title Customize Category for Category Group
        #edit_category_group_mapping.modal-body
          %p Hello
        .modal-footer
          %button.btn.btn-default(type='button' data-dismiss="modal") Close
          %button.btn.btn-primary(type="button") Save changes

app/views/categories/destroy.js.erb
$("#category_list_item_<%=@category.id%>").fadeOut();

app/views/categories/edit.html.haml
= render partial:'form_with_category_group', locals:{ category:@category }

app/views/categories/edit.js.haml
- modal_id = params[:modal_id] || 'category_group_mapping_modal'
$('##{modal_id}').modal('show');

app/views/categories/new.html.erb
<%= render partial:'form_with_category_group', locals:{ category: @category } %>

app/views/categories/show.html.haml
- content_for(:head_extra) do

  = render(partial: 'items/items_search_head')

.container

  .row(style="display: none;")
    %ol.breadcrumb
      %li
        = link_to('For Sale Items', items_path)
      - if @category
        %li
          = link_to(@category.name, category_title_path(@category, title: @category.title_path) )
      - if params[:query].present?
        %li(class='active')
          %strong.text-success &ldquo;#{params[:query]}&rdquo;

  = section_tabs(css_class: 'content-width center-block')

  .section-gap

  %div(id='items_container' class='row content-width center-block')
    %ul(id="tiles")
      - @items_search.results.each do|item|
        %li
          = render(partial: 'items/item_thumbnail', locals:{ item: item, favorite_item_ids: @favorite_item_ids } )

    .clearfix

  %div(id="loader-circle" class='row content-width center-block')
    %span(class='vertical-center') Loading ...

  -# = pagination_links @items_search.results, { is_active: true }

  .row
    %p.clearfix

  - if auth_user && auth_user.is_a?(Child)
    = render(partial: 'home/bottom_tabbar')

app/views/categories/update.js.erb
$("#category_list_item_<%=@category.id%> male_icon_img").attr("src", "<%=@category.male_icon_url.to_s%>");
$("#category_list_item_<%=@category.id%> male_camera_bg_img").attr("src", "<%=@category.male_camera_background_url.to_s%>");
$("#category_list_item_<%=@category.id%> female_icon_img").attr("src", "<%=@category.female_icon_url.to_s%>");
$("#category_list_item_<%=@category.id%> female_camera_bg_img").attr("src", "<%=@category.male_camera_background_url.to_s%>");

app/views/categories/user_categories.html.haml
- content_for(:head_extra) do

  = javascript_include_tag 'items'


.container
  = section_tabs(css_class: 'content-width center-block')

  .section-gap

  %div(class="content-width center-block text-center")
    - @categories.each_with_index do|category, index|
      - if index % 3 == 0
        .row
      = make_category_cell(category, auth_user)
      
  .section-gap