config/routes.rb
KidsToys::Application.routes.draw do



  use_doorkeeper

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match 'admin' => 'users/admin#index', :via => :get, :as => 'admin'
  match 'admin' => 'users/admin#login', :via => :post, :as => 'admin_login'
  match 'admin/users' => 'users/admin#users', :via => :get, :as => 'admin_users'
  match 'admin/update_user/:id' => 'users/admin#update_user', :via => [:put, :post], :as => 'admin_update_user'
  match 'admin/delete_user/:id' => 'users/admin#delete_user', :via => [:delete], :as => 'admin_delete_user'
  match 'admin/schools' => 'users/admin#schools', :via => :get, :as => 'admin_schools'
  match 'admin/notifications' => 'users/admin#notifications', :via => :get, :as => 'admin_notifications'
  match 'admin/logout' => 'users/admin#logout', :via => [:get, :delete], :as => 'admin_logout'

  match 'question_answers/update_all' => 'question_answers#update_all', via: [:put, :post], as: 'update_all_question_answers'
  resources :question_answers, except:[:show]

  resources :item_comments

  resources :cart_items, module: 'carts'

  match 'schools/admin' => 'schools#admin', :via => :get, :as => :schools_admin
  match 'schools/admin/:id' => 'schools#admin_edit', :via => :get, :as =>  :schools_admin_edit
  match 'schools/admin/:id' => 'schools#admin_update', :via => :post, :as => :schools_admin_update
  match 'schools/admin/:id' => 'schools#admin_destroy', :via=> :delete, :as => :schools_admin_destroy
  resources :schools, path: '/schools'

  match '/demo' => 'items#demo'

  namespace :inventory do
    resources :manager, :only => [:index] do

    end
    match 'activate' => 'manager#activate', as: 'activate_item'
    match 'approve' => 'manager#approve', as: 'approve_item'
    match 'deactivate' => 'manager#deactivate', as: 'deactivate_item'
    match 'decline' => 'manager#decline', as: 'decline_item'

    match 'item_for_approval' => 'manager#item_for_approval_notice', as: 'item_for_approval_notice'
  end


  match 'admin/categories' => 'categories#admin', :as => :admin_categories
  match 'categories/update_all' => 'categories#update_all', as: :update_all_categories, via:[:put, :post]
  resources :categories

  match 'category_groups/update_all' => 'category_groups#update_all', as: :update_all_category_groups, via:[:put, :post]
  match 'category_groups/:id/add_mapping' => 'category_groups#add_mapping', as: :add_category_group_mapping, via:[:put, :post]
  match 'category_groups/:id/add_curated_category' => 'category_groups#add_curated_category', as: :add_curated_category, via:[:put, :post]
  resources :category_groups
  resources :category_group_mappings, only: [:edit, :update]

  match 'categories/:id(/:title)' => 'categories#show', :as => :category_title
  match 'user_categories' => 'categories#user_categories', :as => :user_categories

  get 'account/confirm' => 'account_confirmation#index', as: :account_confirmation
  get 'account/credit_card' => 'account_confirmation#credit_card', as: :account_credit_card
  get 'account/driver_license' => 'account_confirmation#driver_license', as: :account_driver_license
  post 'account/driver_license' => 'account_confirmation#upload_driver_license', as: :account_upload_driver_license
  post 'account/confirm/payment' => 'account_confirmation#authorize_payment', as: :account_confirmation_payment
  get 'account/confirmed' => 'account_confirmation#account_confirmed', as: :account_confirmed
  #####################
  # Trade

  resources :trades, module: 'trading', except: [:edit, :update, :create], as: 'trade'
  match 'trades/(:id)(.:format)' => 'trading/trades#create', as: 'create_trade', via: :post
  match 'trades/(:id)(.:format)' => 'trading/trades#reply', as: 'reply_trade', via: :put
  match 'trades/:id/comments(.:format)' => 'trading/trades#list_comments', as: 'trade_comments', via: :get
  match 'trades/:id/comments(.:format)' => 'trading/trades#comments', as: 'create_trade_comments', via: :post
  match 'trades/:id/accept(.:format)' => 'trading/trades#accept', as: 'accept_trade', via: :post
  match 'trades/:id/decline(.:format)' => 'trading/trades#decline', as: 'decline_trade', via: :delete
  match 'trades/:id/cancel(.:format)' => 'trading/trades#destroy', as: 'cancel_trade', via: [:put, :post, :delete]
  match 'trades/:id/pick_meeting(.:format)' => 'trading/trades#pick_meeting', as: 'pick_meeting', via: [:put, :post]
  match 'trades/:id/respond_to_meeting(.:format)' => 'trading/trades#respond_to_meeting', as: 'respond_to_meeting', via: [:put, :post]
  match 'trades/:id/confirm(.:format)' => 'trading/trades#confirm_completion', as: 'confirm_completion', via: [:put, :post]
  match 'trades/:id/pack(.:format)' => 'trading/trades#confirm_packed', as: 'confirm_packed', via: [:put, :post]
  match 'trades/:id/completed(.:format)' => 'trading/trades#completed', as: 'completed_change', via: [:put, :post]

  resources :buy_requests, module: 'trading', only: [:new, :create, :show]
  match 'buy_requests/(:id)/accept(.:format)' => 'trading/buy_requests#accept', as: 'accept_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/decline(.:format)' => 'trading/buy_requests#decline', as: 'decline_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/confirm(.:format)' => 'trading/buy_requests#confirm', as: 'confirm_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/sold(.:format)' => 'trading/buy_requests#sold', as: 'sold_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/not_sold(.:format)' => 'trading/buy_requests#not_sold', as: 'not_sold_buy_request', via: [:put, :post]

  #####################
  # Notifications

  resources :notifications, module: 'users', only: [:index, :show] do
    member do
      delete 'delete'
    end
  end
  match 'notifications/archive' => 'users/notifications#archive', as: 'archive_notifications', via: :put
  match '/notifications/push' => 'users/notifications#send_push_notification', as: 'send_push_notification', via: [:put, :post]
  match '/notifications_count(.:format)' => 'users/notifications#count', as: 'notifications_count', via: :get

  root :to => 'home#home'
  get "/home/:version" => "home#home"
  get "/terms" => "home#terms"
  get "/privacy" => "home#privacy"
  get "/privacy_and_terms" => "home#privacy_and_terms"
  get "/safety" => "home#safety"
  get "/about_us" => "home#about_us"
  get "/faq" => "home#faq"

  match 'tips/update_all' => 'tips#update_all', via: [:put, :post], as: 'update_all_tips'
  resources :tips, except: [:show]

  #####################
  # User

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {registrations: 'users', sessions: 'sessions', passwords: 'passwords'}
  devise_scope :user do
    post '/forgot_password', to: 'passwords#create'
    get '/users/password/edit', to: 'password#edit'
    put '/users/password', to: 'passwords#update'
  end
  #post '/forgot_password' => 'devise/passwords#create'
  #get '/forgot_password'=> 'devise/passwords#edit'

  # Custom routes that still use :users scope
  devise_scope :user do
    get "/users/logout" => "sessions#destroy"
    get "/users/show_current_user", as: "show_current_user"
    get "/users/dashboard", to: "users#dashboard", as: "users_dashboard"
    get "/users/friends", to: "users#friends", as: "users_friends"
    get "/users/:id/items", to: "stores#show", as: "users_items"

    get "/users/children", to: "users/children#index", as: "users_children"
    get "/users/child", to: "users/children#new", as: "users_new_child"
    match '/users/child/:id/school' => 'users/children#school', as: 'child_school', via:[:get]
    match '/users/child/:id/update_school' => 'users/children#update_school', as: 'child_update_school', via:[:put, :post]
    get "/users/child/:id", to: "users/children#edit", as: "users_edit_child"
    post "/users/child/create", to: "users/children#create", as: "users_create_child"
    post '/users/student/create', to: 'users/children#create_student', as: 'users_create_student'
    post "/users/push_notifications", to: "users/user_notification_tokens#create", as: "create_user_notification_tokens"
    post "/users/child/login", to: "users/children#login", as: "users_login_child"
    put "/users/child/:id", to: "users/children#update", as: "users_update_child"
    post "/users/sign_in_as/:id", to: "sessions#sign_in_as", as: "sign_in_as"

    get "/users/:id", to: "users#show", as: "user"
    put "/users/login(.format)", to: "sessions#new"
    put "/users" => "users#update", as: "update_user"

    get '/boundaries', to: 'users/boundaries#index', as: 'boundaries'
    put '/boundaries', to: 'users/boundaries#update', as: 'update_boundaries'

    get  '/users/potential_friends' => 'users/friend_request#index', as: 'potential_friends'
    get '/friend_request/:id' => 'users/friend_request#show', as: 'friend_request'
    post '/friend_request' => 'users/friend_request#create', as: 'create_friend_request'
    match '/friend_request/:id/accept' => 'users/friend_request#accept', as: 'accept_friend_request', via:[:put, :post]
    match '/friend_request/:id/decline' => 'users/friend_request#deny_request', as: 'deny_friend_request', via:[:put, :post]

    # Users APIs
    scope path: '/api/v1' do
      get '/users/followings', to: 'users#followings', as: 'api_get_followings'
      get '/videos/value_prop' => 'sessions#video', via: [:get]
      match '/users/logout' => 'sessions#destroy', via: [:get, :put, :delete], as: 'api_users_logout'

      get  '/users/potential_friends' => 'users/friend_request#index', as: 'api_get_potential_friends'
      post '/users/friend_request' => 'users/friend_request#create', as: 'api_create_friend_request'
      get '/users/friend_request/:id' => 'users/friend_request#show', as: 'api_show_friend_request'
      post '/users/friend_request/:id/accept' => 'users/friend_request#accept', as: 'api_accept_friend_request'

app/models/question_answer.rb
class QuestionAnswer < ActiveRecord::Base
  attr_accessible :question, :answer, :order_index

  before_create :set_defaults!


  def set_defaults!
    if self.order_index.nil?
      max_record = self.class.order('order_index desc').first
      self.order_index = max_record ? max_record.order_index + 1 : 1
    end
  end


  def self.populate_from_yaml_file
    h = YAML::load_file( File.join(Rails.root, 'doc/data/question_answers.yml') )
    list = h.is_a?(Array) ? h : h.values.first
    list.collect do|yml_record|
      create( yml_record.attributes )
    end
    puts "|- Loaded #{list.size} of the total #{count} Questions & Answers"
  end
end

app/controllers/question_answers_controller.rb
class QuestionAnswersController < InheritedResources::Base

  respond_to :js, only: [:destroy]

  before_filter :verify_admin!, except: [:show, :index]


  def index
    if auth_user.is_a?(Admin)
      @page_title = 'Frequently Asked Questions and Answers'

      @question_answers = ::QuestionAnswer.order('order_index asc')

      respond_to do|format|
        format.html
      end
    else
      redirect_to faq_path
    end
  end

  # Batch update of order_index.
  def update_all

    params.each_pair do|k, v|
      if k.to_s =~ /^mapping_(\d+)$/
        cc_id = $1.to_i
        logger.info "| Mapping #{cc_id}: #{v.inspect}"
        ::QuestionAnswer.update(cc_id, v)
      end
    end

    respond_to do|format|
      format.js { render :nothing => true }
      format.html { redirect_to action:'index' }
    end
  end

  protected

  def resource
    ['update_all'].include?(params[:action].to_s) ? nil : super
  end


end

app/helpers/question_answers_helper.rb
module QuestionAnswersHelper


  def answer_to_html(text)
    if (text =~ /^\s*<ul/i )
      text.html_safe
    else
      text.split(/\n[\r]?\n/).collect do|paragraph|
        p_css_class = (paragraph =~ /^\s*<img/i) ? 'faq-tab-img' : 'answer-text'
        content_tag :p, class: p_css_class do
          paragraph.html_safe
        end
      end.join("\n")
    end
  end

end

app/views/question_answers/_form.html.haml
- content_for(:head_extra) do

  :css
    .code-container { padding: 2% 10%; }
    .code-container .faq-content { background-color:#ffffff; }
    .code-container .faq-section-content { padding: 10px; }

    .faq-tab { padding-left: 25px;    margin-top: -12px;}
    .faq-tab li{ background: url("/assets/landing-25/faq-li-sign.png") no-repeat scroll top left rgba(0, 0, 0, 0);text-align: left;  font-family: 'Open Sans', sans-serif; font-weight: 400;list-style-type: none;padding-left: 40px;margin-top: 15px;  font-size: 20px;}

= form_for(@question_answer) do |f|
  - if @question_answer.errors.any?
    #error_explanation
      %h2 #{ pluralize(@question_answer.errors.count, "error") } prohibited this question_and_answer from being saved:
      %ul
        - @question_answer.errors.full_messages.each do |msg|
          %li #{msg}

  .section-gap(style="height:3%;")
  .form-horizontal
    .form-group-lg.row
      = f.label(:question, class:'col-sm-2 control-label text-medium-title')
      .col-sm-10
        = f.text_area(:question, class:'form-control', rows: 3 )
    .section-gap
    .form-group-lg.row
      .col-sm-2.text-right
        = f.label(:answer, class:'control-label text-medium-title')
        %br/
        %a.glyphicon.glyphicon-info-sign
        %a(href="#" data-toggle="modal" data-target="#examples-modal") Examples
      .col-sm-10
        = f.text_area(:answer, class:'form-control', rows: 8 )
    .section-gap
    .form-group-lg.row
      .col-sm-offset-2.col-sm-10
        = f.submit('Submit', class:'btn btn-lg btn-primary', :disable_with => 'Submitting...')

#examples-modal.modal.fade(tabindex="-1" role="dialog" aria-labelledby="myModalLabel")
  .modal-dialog(role="document")
    .modal-content
      .modal-header
        %button(type="button" class="close" data-dismiss="modal" aria-label="Close")
          %span(aria-hidden="true") &times;
        %h4#examples-modal-title.modal-title Examples of Answer

      .modal-body
        %ul
          %li Mainly plain text.
          %li You can embed HTML tags inside, such as &lt;img&gt; or &lt;a&gt;.
          %li Extra empty line between paragraphs would be rendered as gap between them.

      .full-separator

      .modal-body
        .row.code-container
          .form-group-lg
            = text_area_tag('example1', "<img src=\"/assets/landing-25/faq-img.png\">\nFirst paragragh.\n\nSecond paragraph.", {rows: 4, class:'form-control'})
          %h4 Rendered as:
          .faq-content
            .faq-section
              .faq-section-content
                %p.faq-tab-img
                  %img.img-responsive.faq-img(src="/assets/landing-25/faq-img.png")
                %p.answer-text
                  First paragraph.
                %p.answer-text
                  Second paragraph.

      .full-separator

      .modal-body
        .row.code-container
          .form-group-lg
            = text_area_tag('example1', "<ul class=\"faq-tab\">\n\t<li>Your child browses items posted by kids in their circle.</li>\n\t<li>When they see something they like, they select itand invite the owner to check out their stuff. </li>\n</ul>", {rows: 5, class:'form-control'})
          %h4 Rendered as:
          .faq-content
            .faq-section
              .faq-section-content
                %ul.faq-tab
                  %li Your child browses items posted by kids in their circle.
                  %li When they see something they like, they select itand invite the owner to check out their stuff. </li>

app/views/question_answers/destroy.js.erb
$("#qa_li_<%= @question_answer.id %>").fadeOut();

app/views/question_answers/edit.html.haml
.container
  .section-gap
  %p.pull-left.normal-weight.text-medium-title(style="margin:0 2% 0 0;")
    %a(href='/admin') ADMIN
    %span.gray-title-color - Question &amp; Answer
  .clearfix

  = render 'form'

  = link_to ' Back', question_answers_path, class:'glyphicon glyphicon-chevron-left'

app/views/question_answers/index.html.haml
- content_for(:footer_extra) do
  :javascript
    $(function () {
      $('[data-toggle="tooltip"]').tooltip();

      $("#qa_list").sortable({
        update: function(event, ui) {
          var children = $(this).children();
          var order = 1;
          for (var ci = 0; ci < children.length; ci++) {
            if (children[ci].tagName == "LI")
            {
              var id = $(children[ci]).attr("data");
              $("#mapping_" + id +"_order_index").val(order);
              order++;
            }
          }
          var saveOrderingClass = $("#save_ordering_button").attr("class");
          if (saveOrderingClass && saveOrderingClass.indexOf("btn-primary") == -1 ) {
            $("#save_ordering_button").attr("class", saveOrderingClass + " btn-primary");
          }
        }
      });
    });

.container
  .section-gap
  %p.pull-left.normal-weight.text-medium-title(style="margin:0 2% 0 0;")
    %a(href='/admin') ADMIN
    %span.gray-title-color - Questions &amp; Answers
  .clearfix

  = form_tag(update_all_question_answers_path, method: :put, remote:true, id:'question_answers_form', name:'question_answers_form') do
    - if auth_user.is_a?(Admin)
      %a.btn.btn-success.pull-right(href="#{new_question_answer_path}" title="New Question & Answer") New
      = submit_tag('Save Ordering', class:'btn pull-right', disable_with:'Saving Ordering ...', id:'save_ordering_button', style:'margin: 0 25px 0 5px;')
      %span.pull-right.light-blue-color You can drag up/down to re-order and press ->
      .clearfix
    .section-gap
    #qa_box
      %ul#qa_list.list-group
        - @question_answers.each_with_index do|qa, index|
          %li.list-group-item(id="qa_li_#{qa.id}" data="#{qa.id}")
            %input(type='hidden' name="mapping_#{qa.id}[order_index]" id="mapping_#{qa.id}_order_index" value="#{index}")/
            #{qa.question}
            = link_to(' ', question_answer_path(qa), remote:true, method:'delete', confirm:'Are you sure to delete this Q&A?', class:'glyphicon glyphicon-remove pull-right', title:'Delete This Question & Answer' )
            %a.glyphicon.glyphicon-pencil.pull-right(href="#{edit_question_answer_path(qa)}" title="Edit This Question & Answer") &nbsp;

app/views/question_answers/new.html.haml
.container
  .row
    .section-gap
    %p.pull-left.normal-weight.text-medium-title(style="margin:0 2% 0 0;")
      %a(href='/admin') ADMIN
      %span.gray-title-color - New Question &amp; Answer
    .clearfix

    = render 'form'